# Part 2 - Numpy
Adapted from [GitHub - jakevdp/PythonDataScienceHandbook: Python Data Science Handbook: full text in Jupyter Notebooks](https://github.com/jakevdp/PythonDataScienceHandbook),[NumPy Tutorial](https://www.tutorialspoint.com/numpy), [NumPy Reference — NumPy v1.13 Manual](https://docs.scipy.org/doc/numpy-1.13.0/reference/) and personal insights. 

### Python Data Types

Python variables are dynamically typed. Every variable is an object unlike other statically typed languages.

The intrepretor must inspect these objects during runtime, to get more information like their type. This means there are a lot more steps in operation used in Python, than a language like C and this is the main reason why it is slower.

A exmple of a benefit of dynamic typing is that you get have heterogenous list.

In [65]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### Why Use Numpy? 

Libraries like Numpy make operations on lists faster because they use homegenous (fixed type lists). This means that the data in these lists can be more densely packed, allowing them to benefit from locality of reference. 

Numpy operations are also implemented in C, which avoids cost of dynamic type checking and other checks specific to dynamic languages.

### Dynamic Type vs Fixed Type lists
Efficiency vs Flexibility tradeoff

![array_vs_list.png](https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/be23269c7eb119e093a6d5ce91e464f5e686d9ab/notebooks/figures/array_vs_list.png)
From: [PythonDataScienceHandbook/02.01-Understanding-Data-Types.ipynb at be23269c7eb119e093a6d5ce91e464f5e686d9ab · jakevdp/PythonDataScienceHandbook · GitHub](https://github.com/jakevdp/PythonDataScienceHandbook/blob/be23269c7eb119e093a6d5ce91e464f5e686d9ab/notebooks/02.01-Understanding-Data-Types.ipynb)

*************
# Numpy Arrays
- Efficient storage of array-based data
- Efficient operations on the data

## 2.1 Creating Numpy Arrays

In [66]:
import numpy as np

## 2.1.1 From python lists
### From python lists - no explicit type

In [67]:
a = np.array([1, 4, 2, 5, 3])
print(a)
a.dtype

[1 4 2 5 3]


dtype('int64')

### From python lists - explicit type

In [68]:
b = np.array([1, 2, 3, 4], dtype="float32")
print(b)
b.dtype

[1. 2. 3. 4.]


dtype('float32')

## 2.1.2 From scratch

### 1-d

In [69]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 3 * 5 array

In [70]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [71]:
np.random.normal(0, 1, (3, 3))

array([[-0.05503512, -0.10731045,  1.36546718],
       [-0.09769572, -2.42595457, -0.4530558 ],
       [-0.470771  ,  0.973016  , -1.27814912]])

### Identity Matrix

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2.2 NumPy Array Attributes

In [73]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [74]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## 2.3 Numpy Array Manipulations

### 2.3.1 Array Indexing

In [75]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
print(a)
print(a[1])

[1 4 2 5 3]
4


### Multi-dimensional arrays - 2d array

In [76]:
np.random.seed(0)
b = np.random.randint(10, size=(3, 4)) 
print(b)
print(x2[2, 2])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
7


### 2.3.2 Array Slicing - General Formulae `x[start:stop:step]`

### 1d

In [77]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### Select first 5 elements/ last 5

In [78]:
print("First 5:",a[:5])
print("Last 5 :",a[5:])

First 5: [0 1 2 3 4]
Last 5 : [5 6 7 8 9]


### Sub arrays

In [79]:
print(a[4:7]) #From index 4 inclusive to index 7 exclusive(not inclusive of index 7). 

[4 5 6]


### Multidimensional Arrays

### 2d Sub arrays

In [80]:
np.random.seed(0)
b = np.random.randint(10, size=(3, 4))
print(b)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [81]:
print(b[:2, :3] )

[[5 0 3]
 [7 9 3]]


### Printing columns - column 0

In [82]:
print(b[:,0])

[5 7 2]


### Printing rows - row 0

In [83]:
print(b[0,:])

[5 0 3 3]


## 2.3.3 Reshaping Arrays

In [84]:
- Convert 1d array into 2d row vector

SyntaxError: invalid syntax (<ipython-input-84-3ec5435b338b>, line 1)